# Generated by Django 4.0.4 on 2022-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='pc',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='GraphicsCard',
        ),
        migrations.AddField(
            model_name='pc',
            name='design',
            field=models.ManyToManyField(to='Shop.design'),
        ),
    ]
