# Generated by Django 4.0.4 on 2022-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_design_remove_harddrive_pc_remove_pc_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harddrive',
            old_name='drive_name',
            new_name='kind_name',
        ),
        migrations.AlterField(
            model_name='pc',
            name='design',
            field=models.ManyToManyField(to='Shop.harddrive'),
        ),
    ]
