# Generated by Django 4.0.4 on 2022-05-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_drive_name_harddrive_kind_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='pc',
            name='pc_logo',
        ),
        migrations.AddField(
            model_name='pc',
            name='drive',
            field=models.ManyToManyField(to='Shop.harddrive'),
        ),
        migrations.RemoveField(
            model_name='pc',
            name='design',
        ),
        migrations.AddField(
            model_name='pc',
            name='design',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Shop.design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='card',
            field=models.ManyToManyField(to='Shop.graphicscard'),
        ),
    ]
